package io.github.hectorvent.floci.services.ses;

import io.github.hectorvent.floci.config.EmulatorConfig;
import io.github.hectorvent.floci.services.ses.model.MessageHeader;
import io.github.hectorvent.floci.services.ses.model.MessageTag;
import io.vertx.core.buffer.Buffer;
import io.vertx.ext.mail.MailAttachment;
import io.vertx.ext.mail.MailClient;
import io.vertx.ext.mail.MailConfig;
import io.vertx.ext.mail.MailMessage;
import io.vertx.ext.mail.StartTLSOptions;
import jakarta.annotation.PreDestroy;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.apache.james.mime4j.dom.Body;
import org.apache.james.mime4j.dom.Entity;
import org.apache.james.mime4j.dom.Header;
import org.apache.james.mime4j.dom.Message;
import org.apache.james.mime4j.dom.Multipart;
import org.apache.james.mime4j.dom.SingleBody;
import org.apache.james.mime4j.dom.TextBody;
import org.apache.james.mime4j.dom.address.Mailbox;
import org.apache.james.mime4j.dom.address.MailboxList;
import org.apache.james.mime4j.dom.field.FieldName;
import org.apache.james.mime4j.field.address.AddressFormatter;
import org.apache.james.mime4j.message.DefaultMessageBuilder;
import org.apache.james.mime4j.message.DefaultMessageWriter;
import org.apache.james.mime4j.stream.Field;
import org.jboss.logging.Logger;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.AbstractExecutorService;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Optional SMTP relay for SES. When {@code floci.services.ses.smtp-host}
 * is configured, sent emails are forwarded to the SMTP server in addition
 * to being stored in the inspection endpoint. When unconfigured (or set
 * to empty string), this class is a no-op.
 *
 * <p>Uses a dedicated Vert.x {@link MailClient} configured directly from
 * {@link EmulatorConfig} rather than wiring through {@code quarkus.mailer.*},
 * which would crash on startup if the host property resolved to empty.
 */
@ApplicationScoped
public class SmtpRelay {

    private static final Logger LOG = Logger.getLogger(SmtpRelay.class);
    private static final long RELAY_TIMEOUT_SECONDS = 30;

    /** SES control header naming the configuration set to apply to a raw send. */
    public static final String HEADER_CONFIGURATION_SET = "X-SES-CONFIGURATION-SET";
    /** SES control header carrying {@code name=value} message tags for a raw send. */
    public static final String HEADER_MESSAGE_TAGS = "X-SES-MESSAGE-TAGS";

    private static final String X_SES_PREFIX = "x-ses-";
    private static final String HEADER_RETURN_PATH = "Return-Path";
    private static final String MESSAGE_ID_DOMAIN = "email.amazonses.com";

    /**
     * Top-level headers of a raw message that are not copied onto the relayed message. The MIME
     * structural headers are regenerated by the Vert.x encoder for the re-built message, so passing
     * the originals through would announce a content type and boundary that no longer describe the
     * body. The address and subject headers are set on {@link MailMessage} directly, and
     * {@code Return-Path} becomes the envelope sender (the receiving MTA writes its own).
     *
     * <p>{@code Date} and {@code Message-ID} are excluded because AWS overrides both: a caller's
     * {@code Date} is replaced with the time the message was accepted, and a caller's
     * {@code Message-ID} with the id SES assigned (SES header fields reference).
     */
    private static final Set<String> SUPPRESSED_RELAY_HEADERS = Set.of(
            "mime-version", "content-type", "content-transfer-encoding",
            "content-disposition", "content-id",
            "from", "to", "cc", "bcc", "subject", "return-path", "message-id", "date");

    private final MailClient mailClient;
    private final ExecutorService relayExecutor;
    private final boolean enabled;

    @Inject
    public SmtpRelay(io.vertx.core.Vertx vertx, EmulatorConfig config) {
        this.enabled = config.services().ses().enabled()
                && config.services().ses().smtpHost()
                        .filter(h -> !h.isBlank())
                        .isPresent();
        if (enabled) {
            this.relayExecutor = Executors.newSingleThreadExecutor(r -> {
                Thread t = new Thread(r, "ses-smtp-relay");
                t.setDaemon(true);
                return t;
            });
            String host = config.services().ses().smtpHost().get();
            int port = config.services().ses().smtpPort();
            LOG.infov("SES SMTP relay enabled: {0}:{1}", host, String.valueOf(port));

            this.mailClient = MailClient.create(vertx, buildMailConfig(config, host, port));
        } else {
            this.relayExecutor = null;
            this.mailClient = null;
        }
    }

    static MailConfig buildMailConfig(EmulatorConfig config, String host, int port) {
        MailConfig mailConfig = new MailConfig()
                .setHostname(host)
                .setPort(port);
        config.services().ses().smtpUser()
                .filter(u -> !u.isBlank())
                .ifPresent(u -> {
                    mailConfig.setUsername(u);
                    config.services().ses().smtpPass()
                            .filter(p -> !p.isBlank())
                            .ifPresent(mailConfig::setPassword);
                });
        String starttls = config.services().ses().smtpStarttls();
        if ("REQUIRED".equalsIgnoreCase(starttls)) {
            mailConfig.setStarttls(StartTLSOptions.REQUIRED);
        } else if ("OPTIONAL".equalsIgnoreCase(starttls)) {
            mailConfig.setStarttls(StartTLSOptions.OPTIONAL);
        } else {
            if (!"DISABLED".equalsIgnoreCase(starttls)) {
                LOG.warnv("Unrecognized smtp-starttls value \"{0}\", defaulting to DISABLED", starttls);
            }
            mailConfig.setStarttls(StartTLSOptions.DISABLED);
        }
        return mailConfig;
    }

    /** Package-private constructor for tests (synchronous executor, mock client). */
    SmtpRelay(MailClient mailClient, boolean enabled) {
        this.mailClient = mailClient;
        // Synchronous executor for deterministic test ordering
        this.relayExecutor = new AbstractExecutorService() {
            private volatile boolean shutdown = false;
            @Override public void execute(Runnable r) { r.run(); }
            @Override public void shutdown() { shutdown = true; }
            @Override public java.util.List<Runnable> shutdownNow() { shutdown = true; return java.util.List.of(); }
            @Override public boolean isShutdown() { return shutdown; }
            @Override public boolean isTerminated() { return shutdown; }
            @Override public boolean awaitTermination(long t, java.util.concurrent.TimeUnit u) { return true; }
        };
        this.enabled = enabled;
    }

    @PreDestroy
    void shutdown() {
        if (relayExecutor != null) {
            relayExecutor.shutdownNow();
        }
        if (mailClient != null) {
            mailClient.close();
        }
    }

    public boolean isEnabled() {
        return enabled;
    }

    /**
     * A structured (non-raw) message to relay. Built with {@link #builder(String)}; every field
     * other than the sender is optional.
     */
    public record RelayMessage(String from, String returnPath,
                               List<String> to, List<String> cc, List<String> bcc,
                               List<String> replyTo,
                               String subject, String bodyText, String bodyHtml,
                               List<MessageHeader> headers,
                               String messageId) {

        public static Builder builder(String from) {
            return new Builder(from);
        }

        public static final class Builder {
            private final String from;
            private String returnPath;
            private List<String> to;
            private List<String> cc;
            private List<String> bcc;
            private List<String> replyTo;
            private String subject;
            private String bodyText;
            private String bodyHtml;
            private List<MessageHeader> headers;
            private String messageId;

            private Builder(String from) {
                this.from = from;
            }

            public Builder returnPath(String returnPath) { this.returnPath = returnPath; return this; }
            public Builder to(List<String> to) { this.to = to; return this; }
            public Builder cc(List<String> cc) { this.cc = cc; return this; }
            public Builder bcc(List<String> bcc) { this.bcc = bcc; return this; }
            public Builder replyTo(List<String> replyTo) { this.replyTo = replyTo; return this; }
            public Builder subject(String subject) { this.subject = subject; return this; }
            public Builder bodyText(String bodyText) { this.bodyText = bodyText; return this; }
            public Builder bodyHtml(String bodyHtml) { this.bodyHtml = bodyHtml; return this; }
            public Builder headers(List<MessageHeader> headers) { this.headers = headers; return this; }
            public Builder messageId(String messageId) { this.messageId = messageId; return this; }

            public RelayMessage build() {
                return new RelayMessage(from, returnPath, to, cc, bcc, replyTo,
                        subject, bodyText, bodyHtml, headers, messageId);
            }
        }
    }

    /**
     * A raw RFC 5322 message to relay verbatim. {@code destinations} is the envelope recipient
     * list; when empty the MIME To / Cc / Bcc headers are used instead.
     */
    public record RawRelayMessage(String from, String returnPath, List<String> destinations,
                                  String rawMessage, String messageId) {
    }

    /**
     * Relays a structured email asynchronously.
     */
    public void relay(RelayMessage message) {
        if (!enabled) {
            return;
        }
        try {
            relayExecutor.execute(() -> doRelay(message));
        } catch (java.util.concurrent.RejectedExecutionException e) {
            LOG.warnv("SMTP relay skipped (executor shutting down) for from={0}", message.from());
        }
    }

    private void doRelay(RelayMessage message) {
        try {
            MailMessage mail = new MailMessage();
            mail.setFrom(message.from());
            applyBounceAddress(mail, message.returnPath(), message.from());
            if (message.to() != null) {
                mail.setTo(message.to());
            }
            if (message.cc() != null) {
                mail.setCc(message.cc());
            }
            if (message.bcc() != null) {
                mail.setBcc(message.bcc());
            }
            if (message.replyTo() != null && !message.replyTo().isEmpty()) {
                mail.addHeader("Reply-To", String.join(", ", message.replyTo()));
            }
            if (message.headers() != null) {
                for (MessageHeader header : message.headers()) {
                    if (!header.isSafe()) {
                        LOG.warnv("SMTP relay: skipping a header with a blank name or CR/LF in its "
                                + "name/value (possible header injection) for from={0}", message.from());
                        continue;
                    }
                    if (FieldName.MESSAGE_ID.equalsIgnoreCase(header.name())) {
                        // AWS overrides a caller-supplied Message-ID, and rejects it outright as a
                        // custom header on Simple / Templated content.
                        continue;
                    }
                    mail.addHeader(header.name(), header.value());
                }
            }
            applyMessageId(mail, message.messageId());
            mail.setSubject(message.subject() != null ? message.subject() : "");
            if (message.bodyText() != null) {
                mail.setText(message.bodyText());
            }
            if (message.bodyHtml() != null) {
                mail.setHtml(message.bodyHtml());
            }

            send(mail);
            LOG.debugv("SMTP relay: sent from={0}, to={1}, subject={2}",
                    message.from(), message.to(), message.subject());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            LOG.warnv(e, "SMTP relay interrupted for from={0}, to={1}", message.from(), message.to());
        } catch (java.util.concurrent.TimeoutException e) {
            LOG.warnv("SMTP relay timed out after {0}s for from={1}, to={2}",
                    RELAY_TIMEOUT_SECONDS, message.from(), message.to());
        } catch (Exception e) {
            LOG.warnv(e, "SMTP relay failed for from={0}, to={1}", message.from(), message.to());
        }
    }

    /**
     * Relays a raw MIME message. Parsed with Mime4j, then sent via MailClient.
     */
    public void relayRaw(RawRelayMessage message) {
        if (!enabled) {
            return;
        }
        try {
            relayExecutor.execute(() -> doRelayRaw(message));
        } catch (java.util.concurrent.RejectedExecutionException e) {
            LOG.warnv("SMTP raw relay skipped (executor shutting down) for from={0}", message.from());
        }
    }

    private void doRelayRaw(RawRelayMessage relayMessage) {
        try {
            byte[] mimeBytes = tryBase64Decode(relayMessage.rawMessage());
            var builder = new DefaultMessageBuilder();
            var message = builder.parseMessage(new ByteArrayInputStream(mimeBytes));

            MailMessage mail = new MailMessage();

            // From. The display name is kept, so "Alice <alice@example.com>" is delivered as the
            // caller wrote it rather than as a bare address.
            if (message.getFrom() != null && !message.getFrom().isEmpty()) {
                mail.setFrom(formatMailbox(message.getFrom().get(0)));
            } else {
                mail.setFrom(relayMessage.from());
            }
            applyBounceAddress(mail, relayMessage.returnPath(), mail.getFrom());

            // SES SendRawEmail: when Destinations is provided, it is the
            // authoritative envelope recipient list — MIME To/Cc headers are
            // display-only and must not add extra SMTP RCPT TO entries.
            List<String> destinations = relayMessage.destinations();
            if (destinations != null && !destinations.isEmpty()) {
                mail.setTo(destinations);
            } else {
                MailboxList toList = message.getTo() != null ? message.getTo().flatten() : null;
                if (toList != null && !toList.isEmpty()) {
                    mail.setTo(formatMailboxes(toList));
                }
                MailboxList ccList = message.getCc() != null ? message.getCc().flatten() : null;
                if (ccList != null && !ccList.isEmpty()) {
                    mail.setCc(formatMailboxes(ccList));
                }
                MailboxList bccList = message.getBcc() != null ? message.getBcc().flatten() : null;
                if (bccList != null && !bccList.isEmpty()) {
                    mail.setBcc(formatMailboxes(bccList));
                }
            }

            // Subject
            mail.setSubject(message.getSubject() != null ? message.getSubject() : "");

            applyMimeParts(message, mail);
            copyRawHeaders(message, mail);
            applyMessageId(mail, relayMessage.messageId());

            send(mail);
            LOG.debugv("SMTP relay: sent raw from={0}, destinations={1}",
                    relayMessage.from(), relayMessage.destinations());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            LOG.warnv(e, "SMTP raw relay interrupted for from={0}", relayMessage.from());
        } catch (java.util.concurrent.TimeoutException e) {
            LOG.warnv("SMTP raw relay timed out after {0}s for from={1}",
                    RELAY_TIMEOUT_SECONDS, relayMessage.from());
        } catch (Exception e) {
            LOG.warnv(e, "SMTP raw relay failed for from={0}", relayMessage.from());
        }
    }

    private void send(MailMessage mail) throws Exception {
        mailClient.sendMail(mail).toCompletionStage().toCompletableFuture()
                .get(RELAY_TIMEOUT_SECONDS, java.util.concurrent.TimeUnit.SECONDS);
    }

    private static void applyBounceAddress(MailMessage mail, String returnPath, String fallback) {
        String bounce = firstNonBlank(returnPath, fallback);
        if (bounce != null) {
            mail.setBounceAddress(extractAngleAddress(bounce));
        }
    }

    private static void applyMessageId(MailMessage mail, String messageId) {
        String header = formatMessageId(messageId);
        if (header != null) {
            mail.addHeader(FieldName.MESSAGE_ID, header);
        }
    }

    /**
     * Formats the Message-ID that AWS stamps on the delivered message. AWS documents that it
     * overrides any caller-supplied Message-ID with its own value, and that the id it assigns is
     * the {@code MessageId} returned to the caller; the local part here is therefore that id. The
     * {@code @email.amazonses.com} domain is not documented and follows observed SES output.
     * Returns null when there is no id to stamp.
     */
    static String formatMessageId(String messageId) {
        if (messageId == null || messageId.isBlank()) {
            return null;
        }
        return "<" + messageId + "@" + MESSAGE_ID_DOMAIN + ">";
    }

    // ──────────────────────────── Raw MIME walking ────────────────────────────

    /** Text bodies and attachments collected from one raw MIME tree. */
    private static final class MimeParts {
        private String text;
        private String html;
        private final List<MailAttachment> attachments = new ArrayList<>();
        private final List<MailAttachment> inline = new ArrayList<>();
    }

    /**
     * Maps the parsed MIME tree onto the outgoing message: the first text/plain and text/html
     * parts become the body, every other leaf becomes an attachment. Parts carrying a
     * {@code Content-ID} are relayed as inline attachments so {@code cid:} references in the HTML
     * body still resolve.
     */
    private static void applyMimeParts(Message message, MailMessage mail) {
        MimeParts parts = new MimeParts();
        collectParts(message, parts);
        if (parts.text != null) {
            mail.setText(parts.text);
        }
        if (parts.html != null) {
            mail.setHtml(parts.html);
        }
        List<MailAttachment> attachments = new ArrayList<>(parts.attachments);
        if (parts.html != null && !parts.inline.isEmpty()) {
            mail.setInlineAttachment(parts.inline);
        } else {
            // The Vert.x encoder only emits inline attachments alongside an HTML body, so without
            // one they would be dropped silently. Relay them as regular attachments instead.
            attachments.addAll(parts.inline);
        }
        if (!attachments.isEmpty()) {
            mail.setAttachment(attachments);
        }
    }

    private static void collectParts(Entity entity, MimeParts parts) {
        Body body = entity.getBody();
        if (body instanceof Multipart multipart) {
            for (Entity part : multipart.getBodyParts()) {
                collectParts(part, parts);
            }
            return;
        }
        if (body instanceof TextBody textBody && !isAttachmentPart(entity)) {
            // Keep the first text/plain and text/html parts encountered so that a second one later
            // in a multipart/mixed message cannot clobber the body already picked up from
            // multipart/alternative.
            String mimeType = entity.getMimeType();
            if ("text/html".equalsIgnoreCase(mimeType)) {
                if (parts.html == null) {
                    parts.html = readTextBody(textBody);
                }
                return;
            }
            if ("text/plain".equalsIgnoreCase(mimeType)) {
                if (parts.text == null) {
                    parts.text = readTextBody(textBody);
                }
                return;
            }
        }
        MailAttachment attachment = toAttachment(entity, body);
        if (attachment == null) {
            return;
        }
        if (attachment.getContentId() != null) {
            parts.inline.add(attachment);
        } else {
            parts.attachments.add(attachment);
        }
    }

    private static boolean isAttachmentPart(Entity entity) {
        return "attachment".equalsIgnoreCase(entity.getDispositionType())
                || entity.getFilename() != null
                || headerValue(entity, FieldName.CONTENT_ID) != null;
    }

    private static MailAttachment toAttachment(Entity entity, Body body) {
        byte[] data = readBodyBytes(body);
        if (data == null) {
            return null;
        }
        MailAttachment attachment = MailAttachment.create()
                .setData(Buffer.buffer(data))
                .setContentType(attachmentContentType(entity))
                .setName(entity.getFilename());
        String disposition = entity.getDispositionType();
        if (disposition != null && !disposition.isBlank()) {
            attachment.setDisposition(disposition);
        }
        String description = headerValue(entity, FieldName.CONTENT_DESCRIPTION);
        if (description != null) {
            attachment.setDescription(description);
        }
        String contentId = headerValue(entity, FieldName.CONTENT_ID);
        if (contentId != null) {
            attachment.setContentId(contentId);
        }
        return attachment;
    }

    /**
     * Decoded bytes of a leaf part. An embedded message/rfc822 part is re-serialized whole so a
     * forwarded message survives the relay.
     */
    private static byte[] readBodyBytes(Body body) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            if (body instanceof SingleBody singleBody) {
                singleBody.writeTo(out);
            } else if (body instanceof Message embedded) {
                new DefaultMessageWriter().writeMessage(embedded, out);
            } else {
                return null;
            }
            return out.toByteArray();
        } catch (IOException e) {
            LOG.warnv(e, "SMTP raw relay: could not read a MIME part, dropping it");
            return null;
        }
    }

    private static String attachmentContentType(Entity entity) {
        String mimeType = entity.getMimeType();
        if (mimeType == null || mimeType.isBlank()) {
            return null;
        }
        String charset = entity.getCharset();
        if (charset != null && !charset.isBlank()
                && mimeType.toLowerCase(Locale.ROOT).startsWith("text/")) {
            return mimeType + "; charset=" + charset;
        }
        return mimeType;
    }

    /**
     * Copies the caller's top-level headers onto the relayed message. The MIME structural,
     * address and subject headers are excluded (see {@link #SUPPRESSED_RELAY_HEADERS}), as are the
     * {@code X-SES-*} control headers: AWS consumes those rather than forwarding them.
     */
    private static void copyRawHeaders(Message message, MailMessage mail) {
        Header header = message.getHeader();
        if (header == null) {
            return;
        }
        for (Field field : header.getFields()) {
            String name = field.getName();
            if (name == null || name.isBlank()) {
                continue;
            }
            String lower = name.toLowerCase(Locale.ROOT);
            if (SUPPRESSED_RELAY_HEADERS.contains(lower) || lower.startsWith(X_SES_PREFIX)) {
                continue;
            }
            String value = field.getBody();
            mail.addHeader(name, value == null ? "" : value.trim());
        }
    }

    private static String readTextBody(TextBody textBody) {
        try {
            Charset charset = StandardCharsets.UTF_8;
            if (textBody.getMimeCharset() != null) {
                try {
                    charset = Charset.forName(textBody.getMimeCharset());
                } catch (Exception e) {
                    LOG.debugv("SMTP raw relay: unknown charset \"{0}\", reading part as UTF-8",
                            textBody.getMimeCharset());
                }
            }
            try (var is = textBody.getInputStream()) {
                return new String(is.readAllBytes(), charset);
            }
        } catch (Exception e) {
            LOG.warnv(e, "SMTP raw relay: could not read a text part, relaying it as empty");
            return "";
        }
    }

    // ──────────────────────────── Raw header parsing ────────────────────────────

    /**
     * Structured headers extracted from a raw RFC 5322 MIME message: the From address, subject,
     * separate To / Cc / Bcc address lists, the {@code Return-Path} envelope sender, and the
     * {@code X-SES-CONFIGURATION-SET} / {@code X-SES-MESSAGE-TAGS} control headers. Empty fields
     * when the corresponding header is missing.
     */
    public record RawMessageHeaders(String from, String subject,
                                    List<String> to, List<String> cc, List<String> bcc,
                                    String returnPath, String configurationSet,
                                    List<MessageTag> messageTags) {
        public static RawMessageHeaders empty() {
            return new RawMessageHeaders("", "", List.of(), List.of(), List.of(),
                    "", "", List.of());
        }
    }

    /**
     * Parses a raw RFC 5322 MIME message (plain or base64-encoded) into
     * {@link RawMessageHeaders}. Returns an empty result when the input is blank
     * or unparseable.
     */
    public static RawMessageHeaders parseRawHeaders(String rawMessage) {
        return parseRawMessage(rawMessage).headers();
    }

    /**
     * The decoded bytes of a raw message, the parsed message ({@code null} when the parser cannot
     * read it) and the headers read off it, from one parse that the send path shares between
     * header extraction and the content scan.
     */
    public record ParsedRawMessage(byte[] bytes, Message message, RawMessageHeaders headers) {}

    public static ParsedRawMessage parseRawMessage(String rawMessage) {
        if (rawMessage == null || rawMessage.isBlank()) {
            return new ParsedRawMessage(new byte[0], null, RawMessageHeaders.empty());
        }
        byte[] mimeBytes = tryBase64Decode(rawMessage);
        Message message = parseMime(mimeBytes);
        return new ParsedRawMessage(mimeBytes, message,
                message == null ? RawMessageHeaders.empty() : headersOf(message));
    }

    /** Parses MIME bytes, or returns {@code null} for anything the parser cannot read. */
    static Message parseMime(byte[] mimeBytes) {
        try {
            return new DefaultMessageBuilder().parseMessage(new ByteArrayInputStream(mimeBytes));
        } catch (Exception | StackOverflowError ignored) {
            // The caller treats an unparseable message as such; there is nothing to diagnose here,
            // and mime4j nests a reader per forwarded message, so a hostile depth overflows too.
            return null;
        }
    }

    private static RawMessageHeaders headersOf(Message message) {
        try {
            String subject = message.getSubject() != null ? message.getSubject() : "";
            List<String> from = message.getFrom() != null
                    ? toMailboxAddresses(message.getFrom()) : List.of();
            List<String> to = message.getTo() != null
                    ? toMailboxAddresses(message.getTo().flatten()) : List.of();
            List<String> cc = message.getCc() != null
                    ? toMailboxAddresses(message.getCc().flatten()) : List.of();
            List<String> bcc = message.getBcc() != null
                    ? toMailboxAddresses(message.getBcc().flatten()) : List.of();
            String returnPath = extractAngleAddress(headerValue(message, HEADER_RETURN_PATH));
            String configurationSet = headerValue(message, HEADER_CONFIGURATION_SET);
            List<MessageTag> messageTags = parseMessageTagsHeader(
                    headerValue(message, HEADER_MESSAGE_TAGS));
            return new RawMessageHeaders(from.isEmpty() ? "" : from.get(0), subject, to, cc, bcc,
                    returnPath == null ? "" : returnPath,
                    configurationSet == null ? "" : configurationSet,
                    messageTags);
        } catch (Exception ignored) {
            // A message whose addresses cannot be read is treated like one without headers.
            return RawMessageHeaders.empty();
        }
    }

    /**
     * Parses an {@code X-SES-MESSAGE-TAGS} header body: a comma-separated list of
     * {@code name=value} pairs. Entries without a name are skipped.
     */
    static List<MessageTag> parseMessageTagsHeader(String value) {
        if (value == null || value.isBlank()) {
            return List.of();
        }
        List<MessageTag> tags = new ArrayList<>();
        for (String pair : value.split(",")) {
            int separator = pair.indexOf('=');
            if (separator < 0) {
                continue;
            }
            String name = pair.substring(0, separator).trim();
            if (name.isEmpty()) {
                continue;
            }
            tags.add(new MessageTag(name, pair.substring(separator + 1).trim()));
        }
        return List.copyOf(tags);
    }

    /**
     * Returns the flat list of recipients (To + Cc + Bcc) parsed from a raw RFC 5322
     * MIME message. Convenience wrapper around {@link #parseRawHeaders}.
     */
    public static List<String> parseRawRecipients(String rawMessage) {
        RawMessageHeaders h = parseRawHeaders(rawMessage);
        List<String> all = new ArrayList<>();
        all.addAll(h.to());
        all.addAll(h.cc());
        all.addAll(h.bcc());
        return all;
    }

    private static String headerValue(Entity entity, String name) {
        Header header = entity.getHeader();
        if (header == null) {
            return null;
        }
        Field field = header.getField(name);
        if (field == null || field.getBody() == null) {
            return null;
        }
        String value = field.getBody().trim();
        return value.isEmpty() ? null : value;
    }

    /** Unwraps the {@code <addr@example.com>} form used by Return-Path and friends. */
    static String extractAngleAddress(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        if (trimmed.startsWith("<") && trimmed.endsWith(">") && trimmed.length() > 2) {
            return trimmed.substring(1, trimmed.length() - 1).trim();
        }
        return trimmed;
    }

    private static String firstNonBlank(String... values) {
        for (String value : values) {
            if (value != null && !value.isBlank()) {
                return value;
            }
        }
        return null;
    }

    /**
     * Renders a mailbox for a relayed header, keeping any display name. Distinct from
     * {@link #toMailboxAddresses}, which yields the bare addresses that the envelope, the
     * suppression checks and the published events work with.
     */
    private static String formatMailbox(Mailbox mailbox) {
        return AddressFormatter.DEFAULT.encode(mailbox);
    }

    private static List<String> formatMailboxes(MailboxList list) {
        List<String> addresses = new ArrayList<>();
        for (Mailbox mailbox : list) {
            addresses.add(formatMailbox(mailbox));
        }
        return addresses;
    }

    private static List<String> toMailboxAddresses(MailboxList list) {
        List<String> addresses = new ArrayList<>();
        for (Mailbox mailbox : list) {
            addresses.add(mailbox.getAddress());
        }
        return addresses;
    }

    /**
     * Decodes the {@code RawMessage.Data} blob, which SDK callers send base64-encoded but which
     * Floci also accepts as plain RFC 5322 text.
     *
     * <p>The alphabet is checked before decoding rather than relying on the decoder to reject
     * plain text: {@link Base64#getMimeDecoder()} skips characters outside the base64 alphabet, so
     * a plain-text message decodes into garbage whenever the remaining alphabet characters happen
     * to form a valid length. A real RFC 5322 message always carries a header separator, which is
     * not in the alphabet, so the check separates the two cases reliably.
     */
    static byte[] tryBase64Decode(String data) {
        if (looksBase64Encoded(data)) {
            try {
                return Base64.getMimeDecoder().decode(data);
            } catch (IllegalArgumentException e) {
                LOG.debugv("SES raw message looked base64-encoded but did not decode, "
                        + "treating it as plain text");
            }
        }
        return data.getBytes(StandardCharsets.UTF_8);
    }

    private static boolean looksBase64Encoded(String data) {
        boolean sawPayload = false;
        for (int i = 0; i < data.length(); i++) {
            char c = data.charAt(i);
            if (c == '\r' || c == '\n' || c == ' ' || c == '\t' || c == '=') {
                continue;
            }
            if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')
                    || c == '+' || c == '/') {
                sawPayload = true;
                continue;
            }
            return false;
        }
        return sawPayload;
    }
}
